# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRGuard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRGuard
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftyRSA'
  pod 'CryptoSwift'
  pod 'SQLite.swift', '0.11.6'
end
